In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [ ]:
df=pd.read_csv("nbaplayersdraft.csv")
df

,id,year,rank,overall_pick,team,player,college,years_active,games,minutes_played,points,total_rebounds,assists,field_goal_percentage,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
0,1,1989,1,1,SAC,Pervis Ellison,Louisville,11.0,474.0,11593.0,4494.0,3170.0,691.0,0.510,0.050,0.689,24.5,9.5,6.7,1.5,21.8,0.090,-0.5,4.4
1,2,1989,2,2,LAC,Danny Ferry,Duke,13.0,917.0,18133.0,6439.0,2550.0,1185.0,0.446,0.393,0.840,19.8,7.0,2.8,1.3,34.8,0.092,-0.9,4.9
2,3,1989,3,3,SAS,Sean Elliott,Arizona,12.0,742.0,24502.0,10544.0,3204.0,1897.0,0.465,0.375,0.799,33.0,14.2,4.3,2.6,55.7,0.109,0.2,13.5
3,4,1989,4,4,MIA,Glen Rice,Michigan,15.0,1000.0,34985.0,18336.0,4387.0,2097.0,0.456,0.400,0.846,35.0,18.3,4.4,2.1,88.7,0.122,0.8,24.9
4,5,1989,5,5,CHH,J.R. Reid,UNC,11.0,672.0,15370.0,5680.0,3381.0,639.0,0.472,0.135,0.716,22.9,8.5,5.0,1.0,22.5,0.070,-2.9,-3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1917,1918,2021,56,56,CHO,Scottie Lewis,Florida,1.0,2.0,7.0,1.0,0.0,1.0,NaN,NaN,0.500,3.5,0.5,0.0,0.5,0.0,0.164,6.0,0.0
1918,1919,2021,57,57,CHO,Bal≈°a Koprivica,Florida State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919,1920,2021,58,58,NYK,Jericho Sims,Texas,1.0,41.0,555.0,90.0,169.0,21.0,0.722,NaN,0.414,13.5,2.2,4.1,0.5,1.5,0.128,-1.7,0.0
1920,1921,2021,59,59,BRK,RaiQuan Gray,Florida State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1921,1922,2021,60,60,IND,Georgios Kalaitzakis,NaN,1.0,13.0,214.0,86.0,21.0,12.0,0.463,0.385,0.467,16.5,6.6,1.6,0.9,-0.1,-0.024,-7.0,-0.3

In [ ]:
### wenk to Duke and were drafted on or before 2000

In [ ]:
df_1=df[(df['college']=="Duke") & (df['year']<=2000)]
df_1

,id,year,rank,overall_pick,team,player,college,years_active,games,minutes_played,points,total_rebounds,assists,field_goal_percentage,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
1,2,1989,2,2,LAC,Danny Ferry,Duke,13.0,917.0,18133.0,6439.0,2550.0,1185.0,0.446,0.393,0.840,19.8,7.0,2.8,1.3,34.8,0.092,-0.9,4.9
78,79,1990,25,25,POR,Alaa Abdelnaby,Duke,5.0,256.0,3200.0,1465.0,846.0,85.0,0.502,0.000,0.701,12.5,5.7,3.3,0.3,4.8,0.072,-3.8,-1.5
102,103,1990,49,49,DAL,Phil Henderson,Duke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,165,1992,3,3,MIN,Christian Laettner,Duke,13.0,868.0,25760.0,11121.0,5806.0,2224.0,0.480,0.261,0.820,29.7,12.8,6.7,2.6,64.9,0.121,1.0,19.5
209,210,1992,48,48,PHO,Brian Davis,Duke,1.0,68.0,374.0,131.0,55.0,22.0,0.317,0.333,0.735,5.5,1.9,0.8,0.3,0.0,0.000,-4.7,-0.3
222,223,1993,7,7,SAC,Bobby Hurley,Duke,5.0,269.0,4170.0,1032.0,283.0,880.0,0.353,0.272,0.769,15.5,3.8,1.1,3.3,-1.2,-0.014,-5.4,-3.5
254,255,1993,39,39,IND,Thomas Hill,Duke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,273,1994,3,3,DET,Grant Hill,Duke,18.0,1026.0,34776.0,17137.0,6169.0,4252.0,0.483,0.314,0.769,33.9,16.7,6.0,4.1,99.9,0.138,3.0,43.6
298,299,1994,29,29,PHO,Antonio Lang,Duke,6.0,143.0,1395.0,329.0,210.0,50.0,0.455,0.000,0.719,9.8,2.3,1.5,0.3,1.7,0.057,-3.8,-0.6
335,336,1995,12,12,DAL,Cherokee Parks,Duke,9.0,472.0,7459.0,2056.0,1703.0,265.0,0.470,0.211,0.630,15.8,4.4,3.6,0.6,11.8,0.076,-2.4,-0.7
364,365,1995,41,41,HOU,Erik Meek,Duke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,517,1998,20,20,ATL,Roshown McLeod,Duke,3.0,113.0,2130.0,817.0,308.0,124.0,0.409,0.111,0.819,18.8,7.2,2.7,1.1,0.2,0.004,-4.4,-1.3
555,556,1999,1,1,CHI,Elton Brand,Duke,17.0,1058.0,34910.0,16827.0,9040.0,2184.0,0.500,0.095,0.736,33.0,15.9,8.5,2.1,109.6,0.151,2.2,37.3
565,566,1999,11,11,CLE,Trajan Langdon,Duke,3.0,119.0,1738.0,647.0,159.0,152.0,0.416,0.396,0.910,14.6,5.4,1.3,1.3,2.9,0.079,-1.1,0.4
567,568,1999,13,13,SEA,Corey Maggette,Duke,14.0,827.0,23358.0,13198.0,4022.0,1696.0,0.453,0.324,0.822,28.2,16.0,4.9,2.1,62.2,0.128,0.3,13.3
568,569,1999,14,14,MIN,William Avery,Duke,3.0,142.0,1205.0,379.0,93.0,199.0,0.330,0.255,0.714,8.5,2.7,0.7,1.4,-0.9,-0.034,-5.6,-1.1
653,654,2000,41,41,SAS,Chris Carrawell,Duke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_1['team'].value_counts()

DAL    2
MIN    2
PHO    2
LAC    1
POR    1
SAC    1
IND    1
DET    1
HOU    1
ATL    1
CHI    1
CLE    1
SEA    1
SAS    1
Name: team, dtype: int64

In [ ]:
### Have a first name starts with D and drafted in a even year
df_2=df[(df['player'].str.startswith('D')) & (df['year']% 2 == 0)]
df_2

,id,year,rank,overall_pick,team,player,college,years_active,games,minutes_played,points,total_rebounds,assists,field_goal_percentage,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
54,55,1990,1,1,NJN,Derrick Coleman,Syracuse,15.0,781.0,25903.0,12884.0,7232.0,1985.0,0.447,0.295,0.769,33.2,16.5,9.3,2.5,64.3,0.119,1.4,22.3
57,58,1990,4,4,ORL,Dennis Scott,Georgia Tech,10.0,629.0,17983.0,8094.0,1774.0,1296.0,0.417,0.397,0.793,28.6,12.9,2.8,2.1,33.4,0.089,0.2,9.9
68,69,1990,15,15,MIA,Dave Jamerson,Ohio University,3.0,90.0,594.0,306.0,77.0,61.0,0.392,0.277,0.860,6.6,3.4,0.9,0.7,0.2,0.018,-3.9,-0.3
71,72,1990,18,18,SAC,Duane Causwell,Temple,11.0,541.0,9409.0,2648.0,2273.0,243.0,0.507,0.286,0.618,17.4,4.9,4.2,0.4,15.8,0.081,-2.3,-0.7
72,73,1990,19,19,BOS,Dee Brown,Jacksonville University,12.0,608.0,16843.0,6758.0,1569.0,2227.0,0.436,0.357,0.825,27.7,11.1,2.6,3.7,33.4,0.095,0.8,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1734,1735,2018,53,53,OKC,Devon Hall,Virginia,1.0,11.0,81.0,20.0,7.0,13.0,0.200,0.235,0.500,7.4,1.8,0.6,1.2,-0.2,-0.116,-6.7,-0.1
1810,1811,2020,9,9,WAS,Deni Avdija,NaN,2.0,136.0,3241.0,1027.0,687.0,230.0,0.426,0.316,0.729,23.8,7.6,5.1,1.7,3.6,0.054,-2.3,-0.2
1812,1813,2020,11,11,SAS,Devin Vassell,Florida State,2.0,133.0,2993.0,1213.0,480.0,192.0,0.421,0.357,0.840,22.5,9.1,3.6,1.4,4.8,0.077,-0.9,0.8
1831,1832,2020,30,30,BOS,Desmond Bane,TCU,2.0,144.0,3785.0,2009.0,544.0,326.0,0.464,0.435,0.882,26.3,14.0,3.8,2.3,10.1,0.129,1.3,3.2
1834,1835,2020,33,33,MIN,Daniel Oturu,Minnesota,2.0,33.0,188.0,63.0,53.0,10.0,0.431,0.167,0.706,5.7,1.9,1.6,0.3,0.3,0.086,-5.2,-0.2

In [ ]:
df_2['team'].value_counts()

BOS    7
SEA    7
MIL    7
ATL    6
MIA    5
SAS    5
ORL    5
NYK    4
LAL    4
DEN    4
CHI    4
DAL    4
GSW    3
UTA    3
LAC    3
MEM    3
CLE    3
PHO    3
DET    3
SAC    3
WAS    2
NOP    2
NOH    2
NJN    2
TOR    2
IND    2
CHH    2
MIN    2
POR    2
PHI    2
CHA    1
BRK    1
HOU    1
OKC    1
Name: team, dtype: int64